import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { outfit } from "@/fonts";
import GlobalProvider from "@/provider/global-provider";
import {DashboardLaoyout} from "@/components";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={`${outfit.variable} ${outfit.className} antialiased`}>
        <GlobalProvider>
          <DashboardLaoyout>
            {children}
          </DashboardLaoyout>
       </GlobalProvider>
      </body>
    </html>
  );
}
